[project]
name = "aetheromni"
version = "1.5"
description = "Enterprise Multi-Model RAG & Document Intelligence Platform"
requires-python = ">=3.14"
readme = "README.md"
license = { text = "AGPL-3.0" }

[tool.ruff]
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "static_root",
    "media",
    "db.sqlite3",
    "scratch"
]

line-length = 120
target-version = "py313"  # Preserves cross-version exception parenthesization


[tool.ruff.lint]
select = ["E", "F", "W", "I", "C90", "UP", "B", "S", "DJ", "RUF", "A", "ASYNC", "C4", "LOG", "G", "PIE", "PGH", "SIM", "PERF"]
ignore = [
    "S101", "S105", "S106", "E501", "S108", "S603", "E402", "F841", "S310", "B904",
    "S112", "B905", "W291", "W293", "RUF012", "DJ012", "S110", "S607", "RUF002",
    "DJ008", "F821", "SIM108", "SIM105", "PERF401", "A001", "A002", "A003", "G004", "S404", "S308"
]


[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.ruff.lint.isort]
combine-as-imports = true
