apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aether-worker
  namespace: "cs-poc-pfjoxqspipkzqdfmgnqcd3c"
  labels:
    cloud.googleapis.com/location: asia-southeast1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/launch-stage: BETA
    spec:
      serviceAccountName: run-service-account@cs-poc-pfjoxqspipkzqdfmgnqcd3c.iam.gserviceaccount.com
      timeoutSeconds: 900
      containers:
      - image: asia-southeast1-docker.pkg.dev/cs-poc-pfjoxqspipkzqdfmgnqcd3c/aether-repo/aether-web:latest
        name: web
        ports:
        - containerPort: 8080
        env:
        - name: RELEASE_VERSION
          value: "v1.2.283+197fe2c"
        - name: DJANGO_DEBUG
          value: "False"
        - name: GS_BUCKET_NAME
          value: "cs-poc-pfjoxqspipkzqdfmgnqcd3c-media-data-extractor"
        - name: DJANGO_ALLOWED_HOSTS
          value: "localhost,127.0.0.1,.run.app"
        - name: DJANGO_CSRF_TRUSTED_ORIGINS
          value: "https://*.run.app"
        - name: GCP_PROJECT_ID
          value: "cs-poc-pfjoxqspipkzqdfmgnqcd3c"
        - name: GCP_REGION
          value: "asia-southeast1"
        - name: GCP_QUEUE_LOCATION
          value: "asia-southeast1"
        - name: GCP_QUEUE_NAME
          value: "extractor-tasks"
        - name: APP_URL
          value: "https://aether-worker-751922320980.asia-southeast1.run.app"
        - name: SURREAL_NS
          value: "aetheromni"
        - name: SURREAL_DB
          value: "extractor"
        - name: SURREALDB_OFFLINE
          value: "False"
        - name: GOOGLE_CLOUD_PROJECT
          value: "cs-poc-pfjoxqspipkzqdfmgnqcd3c"
        - name: SURREAL_URL
          valueFrom:
            secretKeyRef:
              name: SURREAL_URL
              key: "latest"
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: ADMIN_EMAIL
              key: "latest"
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: ADMIN_USERNAME
              key: "latest"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ADMIN_PASSWORD
              key: "latest"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: DJANGO_SECRET_KEY
              key: "latest"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: GEMINI_API_KEY
              key: "latest"
        - name: SURREAL_USER
          valueFrom:
            secretKeyRef:
              name: SURREAL_USER
              key: "latest"
        - name: SURREAL_PASS
          valueFrom:
            secretKeyRef:
              name: SURREAL_PASS
              key: "latest"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: SUPABASE_URL
              key: "latest"
        - name: SUPABASE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: SUPABASE_PUBLIC_KEY
              key: "latest"
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
  traffic:
  - latestRevision: true
    percent: 100
