# Generated by Django 6.0.6 on 2026-06-16 06:35

import django.db.models.deletion
from django.db import migrations, models

import extractor.models


def create_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_vector_extension, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(max_length=500, upload_to="documents/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("EXTRACTING", "Extracting (Pass 1 OCR)"),
                            ("REFINING", "Refining (Pass 2 Logic)"),
                            ("EMBEDDING", "Generating Embeddings"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="Unknown", max_length=50, null=True)),
                ("author", models.CharField(blank=True, default="Unknown", max_length=255, null=True)),
                ("title", models.CharField(blank=True, default="Untitled", max_length=255, null=True)),
                ("document_type", models.CharField(blank=True, default="PDF", max_length=50, null=True)),
                ("page_count", models.IntegerField(default=0)),
                ("raw_markdown", models.TextField(blank=True)),
                ("refined_markdown", models.TextField(blank=True)),
                ("yaml_metadata", models.TextField(blank=True)),
                ("qa_dataset", models.JSONField(blank=True, default=list)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ("semantic_signature", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.IntegerField()),
                ("text_content", models.TextField()),
                ("embedding", extractor.models.SafeVectorField(blank=True, dimensions=768, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="extractor.sourcedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "chunk_index"],
            },
        ),
    ]
