# Generated by Django 6.0.6 on 2026-06-16 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
    ]
