# Generated by Django 6.0.6 on 2026-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0003_documentchunk_hnsw_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcedocument",
            name="author",
            field=models.CharField(blank=True, default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="document_type",
            field=models.CharField(blank=True, default="PDF", max_length=50),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="language",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="semantic_signature",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="title",
            field=models.CharField(blank=True, default="Untitled", max_length=255),
        ),
    ]
