# Generated by Django 6.0.6 on 2026-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0004_alter_sourcedocument_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_budget_usd",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "source_library_uri",
                    models.URLField(
                        default="https://risala.prh.gov.sa/ar/main-content",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Queued"),
                    ("EXTRACTING", "OCR & Layout Analysis"),
                    ("REFINING", "Semantic Curation"),
                    ("EMBEDDING", "Vector Indexing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
