# Generated by Django 6.0.6 on 2026-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0005_systemsettings_alter_sourcedocument_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="uuid",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
