# Generated by Django 6.0.6 on 2026-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0006_sourcedocument_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="selected_model",
            field=models.CharField(default="auto", max_length=100),
        ),
    ]
