# Generated by Django 6.0.6 on 2026-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0007_systemsettings_selected_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="csrf_trusted_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma-separated list of custom domains/origins to trust for CSRF (e.g. https://my-custom-domain.com).",
            ),
        ),
    ]
