# Generated by Django 6.0.6 on 2026-06-22 01:22

from django.db import migrations, models

import extractor.models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0009_sourcedocument_uploaded_by_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="RAGQueryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(unique=True)),
                ("answer_text", models.TextField()),
                ("sources_json", models.JSONField(blank=True, default=list)),
                ("embedding", extractor.models.SafeVectorField(dimensions=768)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
