# Generated by Django 6.0.6 on 2026-06-29 12:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0011_rework"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
