# Generated by Django 6.0.6 on 2026-07-04 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0012_sourcedocument_retry_count_alter_sourcedocument_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="source_library_uri",
        ),
    ]
