# Generated by Django on 2026-07-06

from django.db import migrations
from decimal import Decimal


def recalculate_costs(apps, schema_editor):
    SourceDocument = apps.get_model("extractor", "SourceDocument")
    # Verified July 2025 Gemini 2.5 rates (standard baseline model): input = $0.30/1M, output = $2.50/1M
    for doc in SourceDocument.objects.filter(status="COMPLETED"):
        if doc.cost_usd > Decimal("0.00"):
            input_cost = Decimal(doc.input_tokens) * Decimal("0.00000030")
            output_cost = Decimal(doc.output_tokens) * Decimal("0.00000250")
            doc.cost_usd = input_cost + output_cost
            doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0013_remove_systemsettings_source_library_uri"),
    ]

    operations = [
        migrations.RunPython(recalculate_costs, reverse_code=migrations.RunPython.noop),
    ]
