# Generated by Django 6.0.6 on 2026-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0014_recalculate_completed_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("auto", "Detected by Browser Locale"),
                    ("USD", "USD ($)"),
                    ("IDR", "IDR (Rp)"),
                    ("SAR", "SAR (SR)"),
                ],
                default="auto",
                max_length=10,
            ),
        ),
    ]
