# Generated by Django 6.0.6 on 2026-07-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0017_raise_budget_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="openrouter_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
