# Generated by Django 6.0.7 on 2026-07-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0019_usermemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcedocument",
            name="doi",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="license_type",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="publication_year",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="sourcedocument",
            name="publisher",
            field=models.CharField(blank=True, default="Unknown", max_length=255),
        ),
    ]
