# Generated by Django 6.0.8 on 2026-08-30 06:38

import uuid

from django.db import migrations, models


def backfill_null_uuids(apps, schema_editor):
    source_document_model = apps.get_model("extractor", "SourceDocument")
    docs_with_null_uuid = source_document_model.objects.filter(uuid__isnull=True)
    for doc in docs_with_null_uuid.iterator(chunk_size=200):
        doc.uuid = uuid.uuid4()
        doc.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0020_sourcedocument_doi_sourcedocument_license_type_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_null_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sourcedocument",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sourcedocument",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
